project_id = "ubxtmbgvibtjtjggjnjm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54324
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54329
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://ubxtmbgvibtjtjggjnjm.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
port = 54330
ip_version = "ipv4"

[functions.ai-copilot-enhanced]
verify_jwt = true

[functions.ai-writing-assistant-enhanced]
verify_jwt = true

[functions.ai-chat-with-context]
verify_jwt = true

[functions.speech-to-text]
verify_jwt = true

[functions.chat-openrouter]
verify_jwt = true

[functions.get-user-profile]
verify_jwt = true

[functions.ai-writing-assistant]
verify_jwt = true

[functions.generate-banner-image]
verify_jwt = true

[functions.banner-storage]
verify_jwt = true

[functions.banner-upload]
verify_jwt = true