// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubxtmbgvibtjtjggjnjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVieHRtYmd2aWJ0anRqZ2dqbmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzIyNjgsImV4cCI6MjA2NzU0ODI2OH0.As1iaW6edJIAUdCyNNfTIiXG3pZRRX4Om9AJ7g4TO3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});